__title__ = 'sd-frost-sta-client'
__version__ = '1.1.45'
__license__ = 'LGPL3'
__author__ = 'Andreas Matheus'
__copyright__ = 'Secure Dimensions'
__contact__ = 'andreas.matheus@secure-dimensions.de'
__url__ = 'https://github.com/securedimensions/STA-Python-Client'
__description__ = 'An improved version of the client library originally developed by Fraunhofer to facilitate interaction with a SensorThings API v1.1 Server'
