__title__ = 'frost_sta_client'
__version__ = '1.1.99'
__license__ = 'LGPL3'
__author__ = 'Andreas Matheus'
__copyright__ = 'Secure Dimensions'
__contact__ = 'andreas.matheus@secure-dimensions.de'
__url__ = 'https://github.com/securedimensions/STA-Python-Client'
__description__ = 'An improved version of the client library to facilitate interaction with a FROST SensorThingsAPI Server originally developed by Fraunhofer'
